### PR TITLE
Fix open & select right sidebar item on load page

### LINKED ISSUE #61: Active menu in level three and beyond
Hi, I have 4 levels of menu. Active (selected) menu works well in first 2 levels but in third and fourth level it do not work properly. It remember selection but collapse the menu. I want them to open so selected menu will be highlighted.

I am not good in javaScript,  can we update this code below?

var url = window.location;
var element = $('ul.nav a').filter(function() {
    return this.href == url || url.href.indexOf(this.href) == 0;
}).addClass('active').parent().parent().addClass('in').parent();

### PR DESCRIPTION
**Pull request by m-zanetti**
When third level item is selected sidebar was not expanded because "ul.nav-second-level" does not have *in* class.

I fixed it setting *active* on current "ul.nav a" and then setting *in* on "ul.nav" parents and *active* on "li" parents of "ul.nav".

This should also fix #61

### CODE REVIEW

**Comment by futuernorn** [comment]
Any chance for this PR getting merged in the near future?

**Comment by r-ryabyy** [comment]
I think it's good for starter package, but seems everything else will depend on backend and their URL structure

**Comment by m-zanetti** [comment]
@r-ryabyy you are right, so i try to fix different link as possible in my new commit:
1) link with only # are skipped #84 
2) by default only pathname is used to matchfor seo url or subpath #58 
3) a data attributes *data-search="true" used on all link with search to match #75

**Comment by m-zanetti** [comment]
Hi David,

what don't you like in my change, it fixes some problem with dropdown left sidebar

**Comment by davidtmiller** [comment]
I was closing out pull requests because I was reconfiguring the repo and needed everything closed unfortunately. You can open a new pull request with your changes to the master branch for review though! Sorry for the inconvenience.

**Pull request closed without merging**
