### PR TITLE
Added composer.json for installation from packagist

### PR DESCRIPTION
**Pull request by foxou33**
Hello,
I've been using you work for quite a while now and i really enjoy it. The only problem is that you don't have a composer package for easy installation in PHP project.
Please accept this pull request. It simply adds a composer.json file which would allow you to submit this package (also you need to create a packagist account).
Thank you in advance.
https://getcomposer.org/
https://packagist.org/

### CODE REVIEW

**Comment by Zeromax** [comment]
:+1:  ;)

**Comment by foxou33** [comment]
Hello,

I just saw that you merged the branch with the composer.json file.
Thanks a lot for that. You should now be able to submit your package on Packagist (https://packagist.org/packages/submit).
This will allow anybody using Composer in PHP projects to easily install and use your theme.
Packagist also provide a GitHub service hook to ensures that your package will always be updated instantly when you push to GitHub (https://packagist.org/about#how-to-update-packages).
Also, you could add this installation method in your README.md and on startbootstrap.com (just like you did with bower).
Note: at the time i added the composer.json file, i thought you could use "iron-summit-media/startbootstrap-sb-admin-2" as a package name. But maybe you should update this to "blackrock-digital/startbootstrap-sb-admin-2".

Thank you in advance.

**Comment by AnatolyRugalev** [comment]
@foxou33 @challgren @Zeromax @davidtmiller 

Looks like, this issue is abandoned.

I added this package from my own packagist account: [iron-summit-media/startbootstrap-sb-admin-2](https://packagist.org/packages/iron-summit-media/startbootstrap-sb-admin-2)

I cannot setup automatic update without repo access. If you want to republish package from another account let me know.

**Comment by Zeromax** [comment]
@AnatolyRugalev @davidtmiller can you please remove me from the maintainer list? sb-admin is not mine it is @davidtmiller and I am not allowed to add me as a maintainer, cause I am not... ;)

**Pull request merged**
